changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
#        - Semver-Major
        - major        
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
#        - Semver-Minor
        - minor        
        - enhancement
    - title: Other Changes
      labels:
        - "*"
